import { Icricketers } from "../models/cricketers";

export const cricketerData : Icricketers[]= [
  {
    id: 1,
    name: 'Rohit Sharma',
    imageUrl:
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjBrTMLgT4T683rNr5epNrb-LoOL-mSfuyBDOaCSGpyIHrUvL3uItIL-xBx5_QyuO47iN2G8v9DcINLF_t-tVjV3vwJ43tje_qK0SjWHNTlYrq3u2MF0FFPqc7oIe2khTWpqjG5iWmxF37gv6WPFEHZRZ-tuN82FdMw4sXUhx6_ODVabPtal8kpu9D6/s1200/Rohit-Sharma.jpg',
    imageTitle: 'Rohit Sharma playing a pull shot',
    role: 'Batsman',
    runs: 11000,
    wickets: 8,
  },
  {
    id: 2,
    name: 'Virat Kohli',
    imageUrl: 'https://e0.365dm.com/25/02/1600x900/skysports-virat-kohli-india_6837817.jpg?20250223171250',
    imageTitle: 'Virat Kohli cover drive',
    role: 'Batsman',
    runs: 13000,
    wickets: 4,
  },
  {
    id: 3,
    name: 'MS Dhoni',
    imageUrl: 'https://images1.wionews.com/images/wion/900x1600/2023/7/6/1688647547758_msdhoniedited070722013442.jpeg',
    imageTitle: 'Dhoni finishing the match',
    role: 'Wicketkeeper',
    runs: 10500,
    wickets: 1,
  },
  {
    id: 4,
    name: 'Hardik Pandya',
    imageUrl: 'https://miro.medium.com/v2/resize:fit:736/1*QXR0BO8Hrk9_JT6Dc-LMdg.jpeg',
    imageTitle: 'Hardik Pandya batting',
    role: 'All-rounder',
    runs: 3500,
    wickets: 70,
  },
  {
    id: 5,
    name: 'Jasprit Bumrah',
    imageUrl: 'https://tse4.mm.bing.net/th/id/OIP.1ucxRSD0BNwxrzgw3MvySgHaEc?rs=1&pid=ImgDetMain&o=7&rm=3',
    imageTitle: 'Bumrah bowling yorker',
    role: 'Bowler',
    runs: 200,
    wickets: 150,
  },
  {
    id: 6,
    name: 'KL Rahul',
    imageUrl: 'https://example.com/rahul.jpg',
    imageTitle: 'KL Rahul batting',
    role: 'Batsman',
    runs: 4500,
    wickets: 0,
  },
  {
    id: 7,
    name: 'Ravindra Jadeja',
    imageUrl: 'https://example.com/jadeja.jpg',
    imageTitle: 'Jadeja celebrating wicket',
    role: 'All-rounder',
    runs: 3000,
    wickets: 190,
  },
  {
    id: 8,
    name: 'Shubman Gill',
    imageUrl: 'https://example.com/gill.jpg',
    imageTitle: 'Gill playing cover drive',
    role: 'Batsman',
    runs: 2500,
    wickets: 0,
  },
  {
    id: 9,
    name: 'Mohammed Shami',
    imageUrl: 'https://example.com/shami.jpg',
    imageTitle: 'Shami fast bowling',
    role: 'Bowler',
    runs: 300,
    wickets: 180,
  },
  {
    id: 10,
    name: 'Rishabh Pant',
    imageUrl: 'https://example.com/pant.jpg',
    imageTitle: 'Pant aggressive batting',
    role: 'Wicketkeeper',
    runs: 3200,
    wickets: 0,
  },
  {
    id: 11,
    name: 'Bhuvneshwar Kumar',
    imageUrl: 'https://example.com/bhuvi.jpg',
    imageTitle: 'Bhuvi swing bowling',
    role: 'Bowler',
    runs: 600,
    wickets: 160,
  },
  {
    id: 12,
    name: 'Yuzvendra Chahal',
    imageUrl: 'https://example.com/chahal.jpg',
    imageTitle: 'Chahal spin bowling',
    role: 'Bowler',
    runs: 100,
    wickets: 170,
  },
];
